/**
 * houston/database/model/cycle.js
 * The database model for project cycles
 *
 * @see houston/database/table/cycle
 *
 * @exports {Object} default - database model for cycles
 */

import Database from 'lib/database'

import * as Base from './base'

/**
 * Cycles
 * Holds all cycle information
 *
 * @extends Base.Model
 */
class Cycles extends Base.Model {

  /**
   * tableName
   *
   * @return {String} - the table name
   */
  get tableName () { return 'cycles' }

  /**
   * issues
   *
   * @return {Object}[] - all the issues generated by this cycle
   */
  issues () {
    return this.hasMany('Log', 'cycle_id')
  }

  /**
   * project
   *
   * @return {Object} - the project this cycle was ran for
   */
  project () {
    return this.belongsTo('Project', 'project_id')
  }

  /**
   * release
   * NOTE: may not always exist
   *
   * @return {Object} - the release this cycle was ran for
   */
  release () {
    return this.belongsTo('Release', 'release_id')
  }
}

export default Database.model('Cycle', Cycles)
